# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glowworm_pb2 as glowworm__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in glowworm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlowwormServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendStatus = channel.unary_unary(
                '/GlowwormService/SendStatus',
                request_serializer=glowworm__pb2.Status.SerializeToString,
                response_deserializer=glowworm__pb2.Ack.FromString,
                _registered_method=True)
        self.ReceiveStatus = channel.unary_unary(
                '/GlowwormService/ReceiveStatus',
                request_serializer=glowworm__pb2.Empty.SerializeToString,
                response_deserializer=glowworm__pb2.Status.FromString,
                _registered_method=True)


class GlowwormServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlowwormServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatus,
                    request_deserializer=glowworm__pb2.Status.FromString,
                    response_serializer=glowworm__pb2.Ack.SerializeToString,
            ),
            'ReceiveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveStatus,
                    request_deserializer=glowworm__pb2.Empty.FromString,
                    response_serializer=glowworm__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GlowwormService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GlowwormService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlowwormService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GlowwormService/SendStatus',
            glowworm__pb2.Status.SerializeToString,
            glowworm__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GlowwormService/ReceiveStatus',
            glowworm__pb2.Empty.SerializeToString,
            glowworm__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
