# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glowworm.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glowworm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglowworm.proto\"2\n\x06Status\x12\r\n\x05phase\x18\x01 \x01(\x01\x12\x19\n\x11natural_frequency\x18\x02 \x01(\x01\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2P\n\x0fGlowwormService\x12\x1b\n\nSendStatus\x12\x07.Status\x1a\x04.Ack\x12 \n\rReceiveStatus\x12\x06.Empty\x1a\x07.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glowworm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=18
  _globals['_STATUS']._serialized_end=68
  _globals['_ACK']._serialized_start=70
  _globals['_ACK']._serialized_end=92
  _globals['_EMPTY']._serialized_start=94
  _globals['_EMPTY']._serialized_end=101
  _globals['_GLOWWORMSERVICE']._serialized_start=103
  _globals['_GLOWWORMSERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
